//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace callSurfinghubAPI.SurfhubAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SurfhubAPI.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFriends", ReplyAction="*")]
        callSurfinghubAPI.SurfhubAPI.GetFriendsResponse GetFriends(callSurfinghubAPI.SurfhubAPI.GetFriendsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFriends", ReplyAction="*")]
        System.Threading.Tasks.Task<callSurfinghubAPI.SurfhubAPI.GetFriendsResponse> GetFriendsAsync(callSurfinghubAPI.SurfhubAPI.GetFriendsRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSigns", ReplyAction="*")]
        callSurfinghubAPI.SurfhubAPI.GetSignsResponse GetSigns(callSurfinghubAPI.SurfhubAPI.GetSignsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSigns", ReplyAction="*")]
        System.Threading.Tasks.Task<callSurfinghubAPI.SurfhubAPI.GetSignsResponse> GetSignsAsync(callSurfinghubAPI.SurfhubAPI.GetSignsRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Updatesigns", ReplyAction="*")]
        callSurfinghubAPI.SurfhubAPI.UpdatesignsResponse Updatesigns(callSurfinghubAPI.SurfhubAPI.UpdatesignsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Updatesigns", ReplyAction="*")]
        System.Threading.Tasks.Task<callSurfinghubAPI.SurfhubAPI.UpdatesignsResponse> UpdatesignsAsync(callSurfinghubAPI.SurfhubAPI.UpdatesignsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFriendsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFriends", Namespace="http://tempuri.org/", Order=0)]
        public callSurfinghubAPI.SurfhubAPI.GetFriendsRequestBody Body;
        
        public GetFriendsRequest() {
        }
        
        public GetFriendsRequest(callSurfinghubAPI.SurfhubAPI.GetFriendsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFriendsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        public GetFriendsRequestBody() {
        }
        
        public GetFriendsRequestBody(string Name) {
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFriendsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFriendsResponse", Namespace="http://tempuri.org/", Order=0)]
        public callSurfinghubAPI.SurfhubAPI.GetFriendsResponseBody Body;
        
        public GetFriendsResponse() {
        }
        
        public GetFriendsResponse(callSurfinghubAPI.SurfhubAPI.GetFriendsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFriendsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFriendsResult;
        
        public GetFriendsResponseBody() {
        }
        
        public GetFriendsResponseBody(string GetFriendsResult) {
            this.GetFriendsResult = GetFriendsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSigns", Namespace="http://tempuri.org/", Order=0)]
        public callSurfinghubAPI.SurfhubAPI.GetSignsRequestBody Body;
        
        public GetSignsRequest() {
        }
        
        public GetSignsRequest(callSurfinghubAPI.SurfhubAPI.GetSignsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSignsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        public GetSignsRequestBody() {
        }
        
        public GetSignsRequestBody(string Name) {
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSignsResponse", Namespace="http://tempuri.org/", Order=0)]
        public callSurfinghubAPI.SurfhubAPI.GetSignsResponseBody Body;
        
        public GetSignsResponse() {
        }
        
        public GetSignsResponse(callSurfinghubAPI.SurfhubAPI.GetSignsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSignsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSignsResult;
        
        public GetSignsResponseBody() {
        }
        
        public GetSignsResponseBody(string GetSignsResult) {
            this.GetSignsResult = GetSignsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatesignsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Updatesigns", Namespace="http://tempuri.org/", Order=0)]
        public callSurfinghubAPI.SurfhubAPI.UpdatesignsRequestBody Body;
        
        public UpdatesignsRequest() {
        }
        
        public UpdatesignsRequest(callSurfinghubAPI.SurfhubAPI.UpdatesignsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatesignsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string signs;
        
        public UpdatesignsRequestBody() {
        }
        
        public UpdatesignsRequestBody(string Name, string signs) {
            this.Name = Name;
            this.signs = signs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatesignsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatesignsResponse", Namespace="http://tempuri.org/", Order=0)]
        public callSurfinghubAPI.SurfhubAPI.UpdatesignsResponseBody Body;
        
        public UpdatesignsResponse() {
        }
        
        public UpdatesignsResponse(callSurfinghubAPI.SurfhubAPI.UpdatesignsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatesignsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdatesignsResult;
        
        public UpdatesignsResponseBody() {
        }
        
        public UpdatesignsResponseBody(string UpdatesignsResult) {
            this.UpdatesignsResult = UpdatesignsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : callSurfinghubAPI.SurfhubAPI.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<callSurfinghubAPI.SurfhubAPI.WebService1Soap>, callSurfinghubAPI.SurfhubAPI.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        callSurfinghubAPI.SurfhubAPI.GetFriendsResponse callSurfinghubAPI.SurfhubAPI.WebService1Soap.GetFriends(callSurfinghubAPI.SurfhubAPI.GetFriendsRequest request) {
            return base.Channel.GetFriends(request);
        }
        
        public string GetFriends(string Name) {
            callSurfinghubAPI.SurfhubAPI.GetFriendsRequest inValue = new callSurfinghubAPI.SurfhubAPI.GetFriendsRequest();
            inValue.Body = new callSurfinghubAPI.SurfhubAPI.GetFriendsRequestBody();
            inValue.Body.Name = Name;
            callSurfinghubAPI.SurfhubAPI.GetFriendsResponse retVal = ((callSurfinghubAPI.SurfhubAPI.WebService1Soap)(this)).GetFriends(inValue);
            return retVal.Body.GetFriendsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<callSurfinghubAPI.SurfhubAPI.GetFriendsResponse> callSurfinghubAPI.SurfhubAPI.WebService1Soap.GetFriendsAsync(callSurfinghubAPI.SurfhubAPI.GetFriendsRequest request) {
            return base.Channel.GetFriendsAsync(request);
        }
        
        public System.Threading.Tasks.Task<callSurfinghubAPI.SurfhubAPI.GetFriendsResponse> GetFriendsAsync(string Name) {
            callSurfinghubAPI.SurfhubAPI.GetFriendsRequest inValue = new callSurfinghubAPI.SurfhubAPI.GetFriendsRequest();
            inValue.Body = new callSurfinghubAPI.SurfhubAPI.GetFriendsRequestBody();
            inValue.Body.Name = Name;
            return ((callSurfinghubAPI.SurfhubAPI.WebService1Soap)(this)).GetFriendsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        callSurfinghubAPI.SurfhubAPI.GetSignsResponse callSurfinghubAPI.SurfhubAPI.WebService1Soap.GetSigns(callSurfinghubAPI.SurfhubAPI.GetSignsRequest request) {
            return base.Channel.GetSigns(request);
        }
        
        public string GetSigns(string Name) {
            callSurfinghubAPI.SurfhubAPI.GetSignsRequest inValue = new callSurfinghubAPI.SurfhubAPI.GetSignsRequest();
            inValue.Body = new callSurfinghubAPI.SurfhubAPI.GetSignsRequestBody();
            inValue.Body.Name = Name;
            callSurfinghubAPI.SurfhubAPI.GetSignsResponse retVal = ((callSurfinghubAPI.SurfhubAPI.WebService1Soap)(this)).GetSigns(inValue);
            return retVal.Body.GetSignsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<callSurfinghubAPI.SurfhubAPI.GetSignsResponse> callSurfinghubAPI.SurfhubAPI.WebService1Soap.GetSignsAsync(callSurfinghubAPI.SurfhubAPI.GetSignsRequest request) {
            return base.Channel.GetSignsAsync(request);
        }
        
        public System.Threading.Tasks.Task<callSurfinghubAPI.SurfhubAPI.GetSignsResponse> GetSignsAsync(string Name) {
            callSurfinghubAPI.SurfhubAPI.GetSignsRequest inValue = new callSurfinghubAPI.SurfhubAPI.GetSignsRequest();
            inValue.Body = new callSurfinghubAPI.SurfhubAPI.GetSignsRequestBody();
            inValue.Body.Name = Name;
            return ((callSurfinghubAPI.SurfhubAPI.WebService1Soap)(this)).GetSignsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        callSurfinghubAPI.SurfhubAPI.UpdatesignsResponse callSurfinghubAPI.SurfhubAPI.WebService1Soap.Updatesigns(callSurfinghubAPI.SurfhubAPI.UpdatesignsRequest request) {
            return base.Channel.Updatesigns(request);
        }
        
        public string Updatesigns(string Name, string signs) {
            callSurfinghubAPI.SurfhubAPI.UpdatesignsRequest inValue = new callSurfinghubAPI.SurfhubAPI.UpdatesignsRequest();
            inValue.Body = new callSurfinghubAPI.SurfhubAPI.UpdatesignsRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.signs = signs;
            callSurfinghubAPI.SurfhubAPI.UpdatesignsResponse retVal = ((callSurfinghubAPI.SurfhubAPI.WebService1Soap)(this)).Updatesigns(inValue);
            return retVal.Body.UpdatesignsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<callSurfinghubAPI.SurfhubAPI.UpdatesignsResponse> callSurfinghubAPI.SurfhubAPI.WebService1Soap.UpdatesignsAsync(callSurfinghubAPI.SurfhubAPI.UpdatesignsRequest request) {
            return base.Channel.UpdatesignsAsync(request);
        }
        
        public System.Threading.Tasks.Task<callSurfinghubAPI.SurfhubAPI.UpdatesignsResponse> UpdatesignsAsync(string Name, string signs) {
            callSurfinghubAPI.SurfhubAPI.UpdatesignsRequest inValue = new callSurfinghubAPI.SurfhubAPI.UpdatesignsRequest();
            inValue.Body = new callSurfinghubAPI.SurfhubAPI.UpdatesignsRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.signs = signs;
            return ((callSurfinghubAPI.SurfhubAPI.WebService1Soap)(this)).UpdatesignsAsync(inValue);
        }
    }
}
